curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'
urlpatterns = [
    path('', views.cursos_list_view, name='cursos_list'),
    path('curso/<int:curso_id>/', views.curso_detail_view, name='curso_detail'),
    path('curso/create', views.curso_create_view, name="curso_create"),
    path('curso/edit/<int:curso_id>', views.curso_edit_view, name="curso_edit"),
    path('curso/delete/<int:curso_id>', views.curso_delete_view, name="curso_delete"),

    path('disciplina/<int:disciplina_id>/', views.disciplina_detail_view, name='disciplina_detail'),
    path('disciplina/create', views.disciplina_create_view, name="disciplina_create"),
    path('disciplina/edit/<int:disciplina_id>', views.disciplina_edit_view, name="disciplina_edit"),
    path('disciplina/delete/<int:disciplina_id>', views.disciplina_delete_view, name="disciplina_delete"),

    path('projeto/<int:projeto_id>/', views.projeto_detail_view, name='projeto_detail'),
    path('projeto/create', views.projeto_create_view, name="projeto_create"),
    path('projeto/edit/<int:projeto_id>', views.projeto_edit_view, name="projeto_edit"),
    path('projeto/delete/<int:projeto_id>', views.projeto_delete_view, name="projeto_delete"),
]

mysite/urls.py
# urls.py

from django.contrib import admin
from django.urls import path, include   # incluir include


urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('curso/', include('curso.urls')),
    path('festivais/', include('festivais.urls')),
    path('artigos/', include('artigos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
]

curso/models.py
from django.db import models

class Curso(models.Model):
    nome = models.CharField(max_length=200)
    apresentacao = models.TextField()
    objetivos = models.TextField()
    competencias = models.TextField()
    codigo_curso = models.CharField(max_length=20, null=True, blank=True)

class AreaCientifica(models.Model):
    nome = models.CharField(max_length=200)
    codigo = models.IntegerField()
    codigo_cnaef = models.TextField()

class Disciplina(models.Model):
    nome = models.CharField(max_length=200)
    ano = models.IntegerField()
    semestre = models.CharField(max_length=20)
    ects = models.IntegerField()
    curricular_unit_readable_code = models.CharField(max_length=20)
    area_cientifica = models.ForeignKey(AreaCientifica, on_delete=models.CASCADE)

class LinguagemProgramacao(models.Model):
    nome = models.CharField(max_length=50)


class Projeto(models.Model):
    nome = models.CharField(max_length=200)
    descricao = models.TextField()
    conceitos_aplicados = models.TextField()
    tecnologias_usadas = models.TextField()
    imagem_url = models.URLField()
    link_video = models.URLField()
    link_github = models.URLField()
    disciplina = models.OneToOneField(Disciplina, on_delete=models.CASCADE)
    linguagens = models.ManyToManyField(LinguagemProgramacao)

class Docente(models.Model):
    nome = models.CharField(max_length=200)
    disciplinas = models.ManyToManyField(Disciplina, related_name="docentes")

# Create your models here.

curso/forms.py
from django import forms
from .models import Curso, Disciplina, Projeto

class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = ['nome', 'apresentacao', 'objetivos', 'competencias', 'codigo_curso']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'apresentacao': forms.TextInput(attrs={'class': 'form-control'}),
            'objetivos': forms.TextInput(attrs={'class': 'form-control'}),
            'competencias': forms.TextInput(attrs={'class': 'form-control'}),
            'codigo_curso': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome': 'Nome do Curso',
            'apresentacao': 'Apresentação',
            'objetivos': 'Objetivos',
            'competencias': 'Competências',
            'codigo_curso': 'Código de Curso',
        }

class DisciplinaForm(forms.ModelForm):
    class Meta:
        model = Disciplina
        fields = ['nome', 'ano', 'semestre', 'ects', 'curricular_unit_readable_code', 'area_cientifica']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'ano': forms.NumberInput(attrs={'class': 'form-control'}),
            'semestre': forms.TextInput(attrs={'class': 'form-control'}),
            'ects': forms.NumberInput(attrs={'class': 'form-control'}),
            'curricular_unit_readable_code': forms.TextInput(attrs={'class': 'form-control'}),
            'area_cientifica': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome': 'Nome da Disciplina',
            'ano': 'Ano',
            'semestre': 'Semestre',
            'ects': 'Créditos ECTS',
            'curricular_unit_readable_code': 'Código Curricular',
            'area_cientifica': 'Área Cientifica',
        }

class ProjetoForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = ['nome', 'descricao', 'conceitos_aplicados', 'tecnologias_usadas', 'imagem_url', 'link_video', 'link_github', 'disciplina', 'linguagens']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control'}),
            'conceitos_aplicados': forms.TextInput(attrs={'class': 'form-control'}),
            'tecnologias_usadas': forms.TextInput(attrs={'class': 'form-control'}),
            'imagem_url': forms.URLInput(attrs={'class': 'form-control'}),
            'link_video':  forms.URLInput(attrs={'class': 'form-control'}),
            'link_github': forms.URLInput(attrs={'class': 'form-control'}),
            'disciplina': forms.Select(attrs={'class': 'form-control'}),
            'linguagens': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome': 'Nome do Projeto',
            'descricao': 'Descrição',
            'conceitos_aplicados': 'Conceitos Aplicados',
            'tecnologias_usadas': 'Tecnologias Usadasd',
            'imagem_url': 'Imagem',
            'link_video': 'Link Video',
            'link_github': 'Link Github',
            'disciplina': 'Disciplina',
            'linguagens': 'Linguagem',
        }

curso/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from .forms import CursoForm, DisciplinaForm, ProjetoForm
from .models import Curso, Disciplina, Projeto

def is_editor(user):
    return user.groups.filter(name="Editores de Curso").exists()

#! Curso
def cursos_list_view(request):
    cursos = Curso.objects.all()
    context = { 'cursos': cursos, 'is_editor': is_editor(request.user)}
    return render(request, 'curso/cursos_list.html', context)

def curso_detail_view(request, curso_id):
    curso = get_object_or_404(Curso, id=curso_id)
    disciplinas = Disciplina.objects.filter(curricular_unit_readable_code__startswith=curso.codigo_curso)
    context = {'curso': curso, 'disciplinas': disciplinas, 'is_editor': is_editor(request.user)}
    return render(request, 'curso/curso_detail.html', context)

@login_required
@user_passes_test(is_editor)
def curso_create_view(request):
    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('curso:cursos_list')
    else:
        form = CursoForm()
    return render(request, 'curso/curso_form.html', {'form': form, 'id_editor': is_editor(request.user)})

@login_required
@user_passes_test(is_editor)
def curso_edit_view(request, curso_id):
    curso = get_object_or_404(Curso, id=curso_id)
    if request.method == 'POST':
        form = CursoForm(request.POST, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('curso:curso_detail')
    else:
        form = CursoForm(instance=curso)
    return render(request, 'curso/curso_form.html', {'form': form, 'curso': curso, 'is_editor': is_editor(request.user)})

@login_required
@user_passes_test(is_editor)
def curso_delete_view(request, curso_id):
    curso = get_object_or_404(Curso, id=curso_id)
    if request.method == 'POST':
        curso.delete()
        return redirect('curso:cursos_list')
    return render(request, 'curso/curso_confirm_delete.html', {'curso': curso, 'is_editor': is_editor(request.user)})

#! Disciplina
def disciplina_detail_view(request, disciplina_id):
    disciplina = get_object_or_404(Disciplina, id=disciplina_id)
    curso_code = disciplina.curricular_unit_readable_code.split('-')[0]
    curso = Curso.objects.filter(codigo_curso=curso_code).first()
    projeto = None
    try:
        projeto = Projeto.objects.get(disciplina=disciplina)
    except Projeto.DoesNotExist:
        pass
    context = {'disciplina': disciplina, 'projeto': projeto, 'curso': curso, 'is_editor': is_editor(request.user)}
    return render(request, 'curso/disciplina_detail.html', context)

@login_required
@user_passes_test(is_editor)
def disciplina_create_view(request):
    if request.method == 'POST':
        form = DisciplinaForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('curso:cursos_list')
    else:
        form = DisciplinaForm()
    return render(request, 'curso/disciplina_form.html', {'form': form, 'is_editor': is_editor(request.user)})

@login_required
@user_passes_test(is_editor)
def disciplina_edit_view(request, disciplina_id):
    disciplina = get_object_or_404(Disciplina, id=disciplina_id)
    if request.method == 'POST':
        form = DisciplinaForm(request.POST, instance=disciplina)
        if form.is_valid():
            form.save()
            return redirect('curso:disciplina_detail')
    else:
        form = DisciplinaForm(instance=disciplina)
    return render(request, 'curso/disciplina_form.html', {'form': form, 'disciplina': disciplina, 'is_editor': is_editor(request.user)})

@login_required
@user_passes_test(is_editor)
def disciplina_delete_view(request, disciplina_id):
    disciplina = get_object_or_404(Disciplina, id=disciplina_id)
    if request.method == 'POST':
        disciplina.delete()
        return redirect('curso:cursos_list')
    return render(request, 'curso/disciplina_confirm_delete.html', {'disciplina': disciplina, 'is_editor': is_editor(request.user)})

#! Projeto
def projeto_detail_view(request, projeto_id):
    projeto = get_object_or_404(Projeto, id=projeto_id)
    disciplina = projeto.disciplina
    curso_code = disciplina.curricular_unit_readable_code.split('-')[0]
    curso = Curso.objects.filter(codigo_curso=curso_code).first()
    context = {'projeto': projeto, 'disciplina': disciplina, 'curso': curso, 'is_editor': is_editor(request.user)}
    return render(request, 'curso/projeto_detail.html', context)

@login_required
@user_passes_test(is_editor)
def projeto_create_view(request):
    if request.method == 'POST':
        form = ProjetoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('curso:cursos_list')
    else:
        form = ProjetoForm()
    return render(request, 'curso/projeto_form.html', {'form': form, 'is_editor': is_editor(request.user)})

@login_required
@user_passes_test(is_editor)
def projeto_edit_view(request, projeto_id):
    projeto = get_object_or_404(Projeto, id=projeto_id)
    if request.method == 'POST':
        form = ProjetoForm(request.POST, instance=projeto)
        if form.is_valid():
            form.save()
            return redirect('curso:projeto_detail')
    else:
        form = ProjetoForm(instance=projeto)
    return render(request, 'curso/projeto_form.html', {'form': form, 'projeto': projeto, 'is_editor': is_editor(request.user)})

@login_required
@user_passes_test(is_editor)
def projeto_delete_view(request, projeto_id):
    projeto = get_object_or_404(Projeto, id=projeto_id)
    if request.method == 'POST':
        projeto.delete()
        return redirect('curso:cursos_list')
    return render(request, 'curso/projeto_confirm_delete.html', {'projeto': projeto, 'is_editor': is_editor(request.user)})



# Create your views here.

curso/templates/curso/curso_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Apagar Curso</h1>
<p>De certeza que quer apagar o curso?</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <a href="{% url 'curso:curso_detail' curso.id} %" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

curso/templates/curso/curso_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ curso.nome }}</h1>
<p><strong>Apresentação:</strong> {{ curso.apresentacao }}</p>
<p><strong>Objetivos:</strong> {{ curso.objetivos }}</p>
<p><strong>Competências:</strong> {{ curso.competencias }}</p>
{% if is_editor %}
<a href="{% url 'curso:curso_edit' curso.id %}" class="btn btn-secondary">Editar</a>
<a href="{% url 'curso:curso_delete' curso.id %}" class="btn btn-danger">Apagar</a>
{% endif %}
<h2>Disciplinas</h2>
<ul>
    {% for disciplina in disciplinas %}
    <li><a href="{% url 'curso:disciplina_detail' disciplina.id %}">{{ disciplina.nome }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

curso/templates/curso/curso_form.html
{% extends 'base.html' %}
{% block content %}
<h1>{% if curso %} Editar Curso {% else %} Criar Curso {% endif %}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">{% if curso %} Editar {% else %} Criar{% endif %}</button>
</form>
{% endblock %}

curso/templates/curso/cursos_list.html
{% extends 'base.html' %}
{% block content %}
<h1>List of Cursos</h1>
{% if is_editor %}
<a href="{% url 'curso:curso_create' %}" class="btn btn-primary">Adicionar Curso</a>
{% endif %}
<ul>
    {% for curso in cursos %}
    <li>
        <a href="{% url 'curso:curso_detail' curso.id %}">{{ curso.nome }}</a>
        - <small>{{ curso.apresentacao|truncatewords:10 }}</small>
    </li>
    {% endfor %}
</ul>
{% endblock %}

curso/templates/curso/disciplina_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Apagar Curso</h1>
<p>De certeza que quer apagar a disciplina?</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <a href="{% url 'curso:disciplina_detail' disciplina.id %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

curso/templates/curso/disciplina_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ disciplina.nome }}</h1>
<p><strong>Ano:</strong> {{ disciplina.ano }}</p>
<p><strong>Semestre:</strong> {{ disciplina.semestre }}</p>
<p><strong>ECTS:</strong> {{ disciplina.ects }}</p>
<p><strong>Área Científica:</strong> {{ disciplina.area_cientifica.nome }}</p>
{% if is_editor %}
<a href="{% url 'curso:disciplina_edit' curso.id %}" class="btn btn-secondary">Editar</a>
<a href="{% url 'curso:disciplina_delete' curso.id %}" class="btn btn-danger">Apagar</a>
{% endif %}
{% if projeto %}
<h2>Projeto Associado</h2>
<p><a href="{% url 'curso:projeto_detail' projeto.id %}">{{ projeto.nome }}</a></p>
{% else %}
<p>Sem projeto associado.</p>
{% endif %}
{% endblock %}

curso/templates/curso/disciplina_form.html
{% extends 'base.html' %}
{% block content %}
<h1>{% if curso %} Editar Disciplina {% else %} Criar Disciplina {% endif %}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">{% if curso %} Editar {% else %} Criar {% endif %}</button>
</form>
{% endblock %}

curso/templates/curso/projeto_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Apagar Projeto</h1>
<p>De certeza que quer apagar o projeto?</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Confirmar</button>
    <a href="{% url 'curso:projeto_detail' projeto.id %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock %}

curso/templates/curso/projeto_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ projeto.nome }}</h1>
<p><strong>Descrição:</strong> {{ projeto.descricao }}</p>
<p><strong>Conceitos Aplicados:</strong> {{ projeto.conceitos_aplicados }}</p>
<p><strong>Tecnologias Usadas:</strong> {{ projeto.tecnologias_usadas }}</p>
<img src="{{ projeto.imagem_url }}" alt="Image of {{ projeto.nome }}" style="width:100%; max-width:600px;">
<a href="{{ projeto.link_video }}">Video Link</a><br>
<a href="{{ projeto.link_github }}">GitHub Link</a>
{% if is_editor %}
<a href="{% url 'curso:projeto_edit' curso.id %}" class="btn btn-secondary">Editar</a>
<a href="{% url 'curso:projeto_delete' curso.id %}" class="btn btn-danger">Apagar</a>
{% endif %}
{% endblock %}

curso/templates/curso/projeto_form.html
{% extends 'base.html' %}
{% block content %}
<h1>{% if curso %} Editar Projeto {% else %} Criar Projeto {% endif %}</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">{% if curso %} Editar {% else %} Criar {% endif %}</button>
</form>
{% endblock %}