bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'
urlpatterns = [
    path('', views.bandas_list_view, name='bandas_list'),
    # Bandas
    path('banda/<int:banda_id>/', views.banda_detail_view, name='banda_detail'),
    path('banda/create/', views.banda_create_view, name='banda_create'),
    path('banda/edit/<int:banda_id>/', views.banda_edit_view, name='banda_edit'),
    path('banda/delete/<int:banda_id>/', views.banda_delete_view, name='banda_delete'),

    # Albums
    path('album/<int:album_id>/', views.album_detail_view, name='album_detail'),
    path('album/create/', views.album_create_view, name='album_create'),
    path('album/edit/<int:album_id>/', views.album_edit_view, name='album_edit'),
    path('album/delete/<int:album_id>/', views.album_delete_view, name='album_delete'),
    
    # Musicas
    path('musica/<int:musica_id>/', views.musica_detail_view, name='musica_detail'),
    path('musica/create/<int:album_id>/', views.musica_create_view, name='musica_create'),
    path('musica/edit/<int:musica_id>/', views.musica_edit_view, name='musica_edit'),
    path('musica/delete/<int:musica_id>/', views.musica_delete_view, name='musica_delete'),
]

curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'
urlpatterns = [
    path('', views.cursos_list_view, name='cursos_list'),
    path('curso/<int:curso_id>/', views.curso_detail_view, name='curso_detail'),
    path('curso/create', views.curso_create_view, name="curso_create"),
    path('curso/edit/<int:curso_id>', views.curso_edit_view, name="curso_edit"),
    path('curso/delete/<int:curso_id>', views.curso_delete_view, name="curso_delete"),

    path('disciplina/<int:disciplina_id>/', views.disciplina_detail_view, name='disciplina_detail'),
    path('disciplina/create', views.disciplina_create_view, name="disciplina_create"),
    path('disciplina/edit/<int:disciplina_id>', views.disciplina_edit_view, name="disciplina_edit"),
    path('disciplina/delete/<int:disciplina_id>', views.disciplina_delete_view, name="disciplina_delete"),

    path('projeto/<int:projeto_id>/', views.projeto_detail_view, name='projeto_detail'),
    path('projeto/create', views.projeto_create_view, name="projeto_create"),
    path('projeto/edit/<int:projeto_id>', views.projeto_edit_view, name="projeto_edit"),
    path('projeto/delete/<int:projeto_id>', views.projeto_delete_view, name="projeto_delete"),
]

mysite/urls.py
# urls.py

from django.contrib import admin
from django.urls import path, include   # incluir include


urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('curso/', include('curso.urls')),
    path('festivais/', include('festivais.urls')),
    path('artigos/', include('artigos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
]

bandas/models.py
from django.db import models

class Banda(models.Model):
    nome = models.CharField(max_length=100)
    nacionalidade = models.CharField(max_length=100)
    ano_criado = models.IntegerField(max_length=4)
    foto = models.ImageField(upload_to = 'uploads/', blank=True)

    def str(self):
        return f'{self.nome} / {self.nacionalidade} / {self.ano_criado}'

class Album(models.Model):
    nome = models.CharField(max_length=100)
    ano_criado = models.IntegerField(max_length=4)
    capa = models.ImageField(upload_to = 'uploads/', blank=True)
    banda = models.ForeignKey(Banda, on_delete=models.CASCADE)

    def str(self):
        return f'{self.nome} - {self.banda} - {self.ano_criado}'

class Musica(models.Model):
    nome = models.CharField(max_length=100)
    link = models.URLField(max_length=100, blank=True)
    ano_criado = models.IntegerField(max_length=4, blank=True)
    duracao = models.DurationField()
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def str(self):
        return f'{self.nome} / {self.ano_criado} / {self.duracao}'

bandas/forms.py
from django import forms
from .models import Musica, Album, Banda

class MusicaForm(forms.ModelForm):
    class Meta:
        model = Musica
        fields = ['nome', 'link', 'ano_criado', 'duracao', 'album']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'link': forms.URLInput(attrs={'class': 'form-control'}),
            'ano_criado': forms.NumberInput(attrs={'class': 'form-control'}),
            'duracao': forms.TimeInput(attrs={'class': 'form-control'}),
            'album': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome': 'Nome da Música',
            'link': 'Link para Ouvir',
            'ano_criado': 'Ano de Criação',
            'duracao': 'Duração',
            'album': 'Álbum',
        }

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['nome', 'ano_criado', 'capa', 'banda']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'ano_criado': forms.NumberInput(attrs={'class': 'form-control'}),
            'capa': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'banda': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome': 'Nome do Album',
            'ano_criado': 'Ano de Criação',
            'capa': 'Capa',
            'banda': 'Banda',
        }

class BandaForm(forms.ModelForm):
    class Meta:
        model = Banda
        fields = ['nome', 'nacionalidade', 'ano_criado', 'foto']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'nacionalidade': forms.TextInput(attrs={'class': 'form-control'}),
            'ano_criado': forms.NumberInput(attrs={'class': 'form-control'}),
            'foto': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome': 'Nome da banda',
            'nacionalidade': 'Nacionalidade da banda',
            'ano_criado': 'Ano de Criação',
        }

bandas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from .models import Banda, Album, Musica
from .forms import MusicaForm, AlbumForm, BandaForm

#! Bandas #!

def bandas_list_view(request):
    bandas = Banda.objects.all()
    is_editor = request.user.groups.filter(name="Editores de Bandas").exists()
    context = {'bandas': bandas,'is_editor': is_editor}
    return render(request, 'bandas/bandas_list.html', context)

def banda_detail_view(request, banda_id):
    banda = get_object_or_404(Banda, id=banda_id)
    albums = banda.album_set.all()
    is_editor = request.user.groups.filter(name="Editores de Bandas").exists()
    context = {'banda': banda, 'albums': albums,'is_editor': is_editor}
    return render(request, 'bandas/banda_detail.html', context)

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def banda_create_view(request):
    if request.method == 'POST':
        form = BandaForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('bandas:bandas_list')
    else:
        form = BandaForm()
    return render(request, 'bandas/banda_create.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def banda_edit_view(request, banda_id):
    banda = get_object_or_404(Banda, id=banda_id)
    if request.method == 'POST':
        form = BandaForm(request.POST, request.FILES, instance=banda)
        if form.is_valid():
            form.save()
            return redirect('bandas:banda_detail', banda_id=banda_id)
    else:
        form = BandaForm(instance=banda)
    return render(request, 'bandas/banda_edit.html', {'form': form, 'banda': banda})

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def banda_delete_view(request, banda_id):
    banda = get_object_or_404(Banda, id=banda_id)
    if request.method == 'GET':
        banda.delete()
        return redirect('bandas:bandas_list')
    return redirect('bandas:banda_detail', banda_id=banda_id)

#! Albuns #!
def album_detail_view(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    musicas = album.musica_set.all()
    is_editor = request.user.groups.filter(name="Editores de Bandas").exists()
    context = {'album': album, 'musicas': musicas,'is_editor': is_editor}
    return render(request, 'bandas/album_detail.html', context)

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def album_create_view(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('bandas:bandas_list')
    else:
        form = AlbumForm()
    return render(request, 'bandas/album_create.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def album_edit_view(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES, instance=album)
        if form.is_valid():
            form.save()
            return redirect('bandas:album_detail', album_id=album.id)
    else:
        form = AlbumForm(instance=album)
    return render(request, 'bandas/album_edit.html', {'form': form, 'album': album})

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def album_delete_view(request, musica_id):
    album = get_object_or_404(Album, id=musica_id)
    if request.method == 'POST':
        album.delete()
        return redirect('bandas:bandas_list')
    return redirect('bandas:album_detail', musica_id=album.id)

#! Musicas #!

def musica_detail_view(request, musica_id):
    musica = get_object_or_404(Musica, id=musica_id)
    album = musica.album
    banda = album.banda
    is_editor = request.user.groups.filter(name="Editores de Bandas").exists()
    context = {'musica': musica, 'album': album, 'banda': banda, 'is_editor': is_editor}
    return render(request, 'bandas/musica_detail.html', context)

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def musica_create_view(request, album_id):
    album = get_object_or_404(Album, id=album_id)
    if request.method == 'POST':
        form = MusicaForm(request.POST, request.FILES)
        if form.is_valid():
            new_musica = form.save(commit=False)
            new_musica.album = album
            new_musica.save()
            return redirect('bandas:album_detail', album_id=album.id)
    else:
        form = MusicaForm()
    return render(request, 'bandas/musica_create.html', {'form': form, 'album': album})

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def musica_edit_view(request, musica_id):
    musica = get_object_or_404(Musica, id=musica_id)
    if request.method == 'POST':
        form = MusicaForm(request.POST, request.FILES, instance=musica)
        if form.is_valid():
            form.save()
            return redirect('bandas:musica_detail', musica_id=musica.id)
    else:
        form = MusicaForm(instance=musica)
    return render(request, 'bandas/musica_edit.html', {'form': form, 'musica': musica})

@login_required
@user_passes_test(lambda u: u.groups.filter(name="Editores de Bandas").exists())
def musica_delete_view(request, musica_id):
    musica = get_object_or_404(Musica, id=musica_id)
    if request.method == 'POST':
        musica.delete()
        return redirect('bandas:bandas_list')
    return redirect('bandas:musica_detail', musica_id=musica.id)

bandas/templates/bandas/album_create.html
{% extends 'base.html' %}
{% block content %}
<h1>Criar Album</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Criar</button>
</form>
{% endblock %}

bandas/templates/bandas/album_detail.html
{% extends 'base.html' %}
{% block title %}{{ album.nome }}{% endblock %}
{% block content %}
<h1>{{ album.nome }}</h1>
<img src="{{ album.capa.url }}" alt="Capa de {{ album.nome }}" style="height: 200px; width: auto;">
<p>Ano: {{ album.ano_criado }} - Banda: {{ album.banda.nome }}</p>
{% if user.is_authenticated and is_editor %}
<div class="btn-group" role="group">
    <a href="{% url 'bandas:album_edit' album.id %}" class="btn btn-secondary">Edit</a>
    <a href="{% url 'bandas:album_delete' album.id %}" class="btn btn-danger"
        onclick="return confirm('Tem a certeza?');">Delete</a>
    <a href="{% url 'bandas:musica_create' album.id %}" class="btn btn-primary">Add Music</a>
</div>
{% endif %}
<h2>Músicas:</h2>
<ul>
    {% for musica in musicas %}
    <li><a href="{% url 'bandas:musica_detail' musica.id %}">{{ musica.nome }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

bandas/templates/bandas/banda_create.html
{% extends 'base.html' %}
{% block title %}Bandas{% endblock %}
{% block content %}
<h1>Create Banda</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

bandas/templates/bandas/banda_detail.html
{% extends 'base.html' %}
{% block title %}{{ banda.nome }}{% endblock %}
{% block content %}
<h1>{{ banda.nome }}</h1>
<img src="{{ banda.foto.url }}" alt="Foto de {{ banda.nome }}" style="height: 200px; width: auto;">
<h3>Nacionalidade: {{ banda.nacionalidade }} - Ano Criado: {{ banda.ano_criado }}</h3>
{% if user.is_authenticated and is_editor %}
<div class="btn-group" role="group">
    <a href="{% url 'bandas:banda_edit' banda.id %}" class="btn btn-secondary">Edit</a>
    <a href="{% url 'bandas:banda_delete' banda.id %}" class="btn btn-danger"
        onclick="return confirm('Tem a certeza?');">Delete</a>
    <a href="{% url 'bandas:album_create' %}" class="btn btn-primary">Create Album</a>
</div>
{% endif %}
<h2>Albuns:</h2>
<ul>
    {% for album in albums %}
    <li><a href="{% url 'bandas:album_detail' album.id %}">{{ album.nome }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

bandas/templates/bandas/banda_edit.html
{% extends 'base.html' %}
{% block title %}Bandas{% endblock %}
{% block content %}
<h1>Edit Banda</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

bandas/templates/bandas/bandas_list.html
{% extends 'base.html' %}
{% block title %}Bandas{% endblock %}
{% block content %}
<h1>Bandas</h1>
{% if user.is_authenticated and is_editor %}
    <a href="{% url 'bandas:banda_create' %}" class="btn btn-primary">Adicionar Banda</a>
{% endif %}
<ul>
    {% for banda in bandas %}
        <li>
            <a href="{% url 'bandas:banda_detail' banda.id %}">{{ banda.nome }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

bandas/templates/bandas/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bandas App</title>
</head>
<body>
    <nav>
        <ul>
            <li><a href="{% url 'bandas:bandas_list' %}">All Bandas</a></li>
            {% if album %}
                <li><a href="{% url 'bandas:banda_detail' album.banda.id %}">{{ album.banda.nome }}</a></li>
                <li><a href="{% url 'bandas:album_detail' album.id %}">{{ album.nome }}</a></li>
            {% elif banda %}
                <li><a href="{% url 'bandas:banda_detail' banda.id %}">{{ banda.nome }}</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

bandas/templates/bandas/musica_create.html
{% extends 'base.html' %}
{% block content %}
<h1>Adicionar musica ao album: {{ album.nome }}</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Adicionar</button>
</form>
{% endblock %}

bandas/templates/bandas/musica_detail.html
{% extends 'base.html' %}
{% block title %}{{ musica.nome }}{% endblock %}
{% block content %}
<h1>{{ musica.nome }}</h1>
<p>Ano: {{ musica.ano_criado }} - Duração: {{ musica.duracao }}</p>
<a href="{{ musica.link }}">Ouvir Música</a>
{% if user.is_authenticated and is_editor %}
<a href="{% url 'bandas:musica_edit' musica.id %}" class="btn btn-secondary">Edit</a>
<form action="{% url 'bandas:musica_delete' musica.id %}" method="post" style="display: inline;"
    onsubmit="return confirm('Tem a certeza?');">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
</form>
{% endif %}
{% endblock %}

bandas/templates/bandas/musica_edit.html
{% extends 'base.html' %}
{% block content %}
<h1>Editar Musica: {{ musica.nome }}</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Guardar</button>
</form>
{% endblock %}