artigos/urls.py
from django.urls import path
from . import views

app_name = 'artigos'

urlpatterns = [
    path('', views.lista_artigos, name='lista_artigos'),
    path('<int:pk>/', views.detalhes_artigo, name='detalhes_artigo'),
    path('create/', views.artigo_create_view, name='artigo_create'),
    path('<int:pk>/edit/', views.artigo_edit_view, name='artigo_edit'),
    path('<int:pk>/delete/', views.artigo_delete_view, name='artigo_delete'),
    path('comment/<int:pk>/edit/', views.comment_edit_view, name='comment_edit'),
    path('comment/<int:pk>/delete/', views.comment_delete_view, name='comment_delete'),
    path('rating/<int:pk>/edit/', views.rating_edit_view, name='rating_edit'),
    path('rating/<int:pk>/delete/', views.rating_delete_view, name='rating_delete'),
]

bandas/urls.py
from django.urls import path
from . import views

app_name = 'bandas'
urlpatterns = [
    path('', views.bandas_list_view, name='bandas_list'),
    # Bandas
    path('banda/<int:banda_id>/', views.banda_detail_view, name='banda_detail'),
    path('banda/create/', views.banda_create_view, name='banda_create'),
    path('banda/edit/<int:banda_id>/', views.banda_edit_view, name='banda_edit'),
    path('banda/delete/<int:banda_id>/', views.banda_delete_view, name='banda_delete'),

    # Albums
    path('album/<int:album_id>/', views.album_detail_view, name='album_detail'),
    path('album/create/', views.album_create_view, name='album_create'),
    path('album/edit/<int:album_id>/', views.album_edit_view, name='album_edit'),
    path('album/delete/<int:album_id>/', views.album_delete_view, name='album_delete'),
    
    # Musicas
    path('musica/<int:musica_id>/', views.musica_detail_view, name='musica_detail'),
    path('musica/create/<int:album_id>/', views.musica_create_view, name='musica_create'),
    path('musica/edit/<int:musica_id>/', views.musica_edit_view, name='musica_edit'),
    path('musica/delete/<int:musica_id>/', views.musica_delete_view, name='musica_delete'),
]

curso/urls.py
from django.urls import path
from . import views

app_name = 'curso'
urlpatterns = [
    path('', views.cursos_list_view, name='cursos_list'),
    path('curso/<int:curso_id>/', views.curso_detail_view, name='curso_detail'),
    path('curso/create', views.curso_create_view, name="curso_create"),
    path('curso/edit/<int:curso_id>', views.curso_edit_view, name="curso_edit"),
    path('curso/delete/<int:curso_id>', views.curso_delete_view, name="curso_delete"),

    path('disciplina/<int:disciplina_id>/', views.disciplina_detail_view, name='disciplina_detail'),
    path('disciplina/create', views.disciplina_create_view, name="disciplina_create"),
    path('disciplina/edit/<int:disciplina_id>', views.disciplina_edit_view, name="disciplina_edit"),
    path('disciplina/delete/<int:disciplina_id>', views.disciplina_delete_view, name="disciplina_delete"),

    path('projeto/<int:projeto_id>/', views.projeto_detail_view, name='projeto_detail'),
    path('projeto/create', views.projeto_create_view, name="projeto_create"),
    path('projeto/edit/<int:projeto_id>', views.projeto_edit_view, name="projeto_edit"),
    path('projeto/delete/<int:projeto_id>', views.projeto_delete_view, name="projeto_delete"),
]

meteo/urls.py
from django.urls import path
from .import views

app_name = "meteo"

urlpatterns = [
    path('weather/today/lisbon/', views.weather_today_lisbon, name='weather_today_lisbon'),
    path('weather/next-5-days/', views.weather_next_5_days, name='weather_next_5_days'),
    path('api/cities/', views.api_list_cities, name='api_list_cities'),
    path('api/weather/today/<int:city_id>/', views.api_weather_today, name='api_weather_today'),
    path('api/weather/next-5-days/<int:city_id>/', views.api_weather_next_5_days, name='api_weather_next_5_days'),
    path('api/description/', views.api_description, name='api_description'),
]

mysite/urls.py
# urls.py

from django.contrib import admin
from django.urls import path, include   # incluir include


urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
    path('noobsite/', include('noobsite.urls')),
    path('pwsite/', include('pwsite.urls')),
    path('bandas/', include('bandas.urls')),
    path('curso/', include('curso.urls')),
    path('festivais/', include('festivais.urls')),
    path('artigos/', include('artigos.urls')),
    path('autenticacao/', include('autenticacao.urls')),
    path('meteo/', include('meteo.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.landing_page, name='landing_page'),
    path('about/', views.about_page, name='about_page'),
    path('techtools/', views.techtools_page, name='techtools_page'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Portfolio{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="{% if request.COOKIES.night_mode == 'true' %}dark-mode{% endif %}">
        <nav class="navbar">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'portfolio:landing_page' %}">Inicio</a>
                <button class="navbar-toggler" id="navbar-toggler">☰</button>
                <div class="navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'portfolio:about_page' %}">MeByMe</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'portfolio:techtools_page' %}">TechTools</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="bandasDropdown">Bandas</a>
                            <div class="dropdown-content">
                                <a href="{% url 'bandas:bandas_list' %}">Lista de Bandas</a>
                                <a href="{% url 'bandas:banda_create' %}">Criar Banda</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="artigosDropdown">Artigos</a>
                            <div class="dropdown-content">
                                <a href="{% url 'artigos:lista_artigos' %}">Lista de Artigos</a>
                                <a href="{% url 'artigos:artigo_create' %}">Criar Artigo</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="cursosDropdown">Cursos</a>
                            <div class="dropdown-content">
                                <a href="{% url 'curso:cursos_list' %}">Lista de Cursos</a>
                                <a href="{% url 'curso:curso_create' %}">Criar Curso</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link" href="#" id="meteoDropdown">Meteo</a>
                            <div class="dropdown-content">
                                <a href="{% url 'meteo:weather_today_lisbon' %}">Weather Today</a>
                                <a href="{% url 'meteo:weather_next_5_days' %}">Next 5 Days</a>
                                <a href="{% url 'meteo:api_description' %}">API Description</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Login</a>
                                <a class="nav-link" href="{% url 'registar' %}">Registar</a>
                            </li>
                        {% endif %}
                        </ul>
                    <button class="btn btn-outline-light" id="toggle-dark-mode">Toggle Dark Mode</button>
                </div>
            </div>
        </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="footer">
        <p>2024</p>
    </footer>

    <script>
        document.getElementById('toggle-dark-mode').addEventListener('click', function() {
            document.body.classList.toggle('dark-mode');
            const isDarkMode = document.body.classList.contains('dark-mode');
            document.cookie = `night_mode=${isDarkMode}; path=/`;
        });

        document.getElementById('navbar-toggler').addEventListener('click', function() {
            document.getElementById('navbarNav').classList.toggle('show');
        });
    </script>
</body>
</html>